version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration:
- Release
- Debug
- Final
platform: x64
build:
  project: Source/Shift Engine.sln
  parallel: true
  verbosity: minimal
cache:
- .git\lfs\objects
clone_script: echo Skip AppVeyor Clone
install:
  - git init %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git remote add origin https://github.com/%APPVEYOR_REPO_NAME%.git
  - git fetch -q origin %APPVEYOR_REPO_COMMIT%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
before_build:
  - ps: git lfs prune | Out-Null